version: "3"
services:
  kakeibosan:
    build: ./
    container_name: app-kakeibosan
    volumes:
      - type: bind
        source: "./"
        target: "/var/kakeibosan/"
      - type: volume
        source: "socket"
        target: "/tmp"
    restart: always
  nginx-kakeibosan:
    image: nginx:latest
    container_name: nginx-kakeibosan
    ports:
      - "8001:80"
    volumes:
      - type: bind
        source: "./web//conf.d/default.conf"
        target: "/etc/nginx/conf.d/default.conf"
      - type: bind
        source: "./kakeibosan/static"
        target: "/var/kakeibosan/kakeibosan/static"
      - type: volume
        source: "socket"
        target: "/tmp"
    restart: always

volumes:
  socket:
