version: "3"
services:
  kakeibosan_app:
    build:
      context: .
      # args:
      #   - ARCH=x86_64
    image: kakeibosan_app
    container_name: kakeibosan_app
    volumes:
      - type: bind
        source: "./"
        target: "/app"
      - type: volume
        source: "socket"
        target: "/tmp"
    restart: always
  kakeibosan_nginx:
    build: ./web
    image: kakeibosan_nginx
    container_name: kakeibosan_nginx
    ports:
      - "8001:80"
    volumes:
      - type: bind
        source: "./kakeibosan/static"
        target: "/app/kakeibosan/static"
      - type: volume
        source: "socket"
        target: "/tmp"
    restart: always

volumes:
  socket:
