version: "3"
services:
  kakeibosan_app:
    build: ./
    image: kakeibosan_app
    container_name: kakeibosan_app
    volumes:
      - type: bind
        source: "./"
        target: "/var/kakeibosan/"
      - type: volume
        source: "socket"
        target: "/tmp"
    restart: always
  kakeibosan_nginx:
    build: ./web
    image: kakeibosan_nginx
    container_name: kakeibosan_nginx
    ports:
      - "8001:80"
    volumes:
      - type: bind
        source: "./web//conf.d/default.conf"
        target: "/etc/nginx/conf.d/default.conf"
      - type: bind
        source: "./kakeibosan/static"
        target: "/var/kakeibosan/kakeibosan/static"
      - type: volume
        source: "socket"
        target: "/tmp"
    restart: always

volumes:
  socket:
