version: "3"
services:
  kakeibosan:
    build: ./
    container_name: app-kakeibosan
    volumes:
      - type: bind
        source: "./kakeibosan"
        target: "/var/kakeibosan/kakeibosan"
      - type: volume
        source: "socket"
        target: "/tmp"
    restart: always
  web:
    image: nginx:latest
    container_name: web-kakeibosan
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: "./web/nginx.conf"
        target: "/etc/nginx/conf.d/default.conf"
      - type: bind
        source: "./kakeibosan/static"
        target: "/var/kakeibosan/kakeibosan/static"
      - type: volume
        source: "socket"
        target: "/tmp"
    restart: always

volumes:
  socket:
