"""empty message

Revision ID: 1acac1fe3407
Revises: 
Create Date: 2022-02-05 16:14:20.305044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1acac1fe3407'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost', sa.Column('is_paid_in_advance', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cost', 'is_paid_in_advance')
    # ### end Alembic commands ###
